apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-example
  template:
    metadata:
      labels:
        app: fastapi-example
    spec:
      containers:
      - name: fastapi-pod
        image: interests/fastapi-example:v003
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9696
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: ClusterIP
  selector:
    app: fastapi-example
  ports:
  - port: 80
    targetPort: 9696
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  labels:
    name: fastapi-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: avisprof.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fastapi-service
            port: 
              number: 80

